/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package kim.spider.schema;

@SuppressWarnings("all")
public class Content extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"Content\",\"namespace\":\"kim.spider.schema\",\"fields\":[{\"name\":\"url\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"bytes\"},{\"name\":\"extend\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"metaData\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"string\"}}}]}");
  public java.lang.CharSequence url;
  public java.nio.ByteBuffer content;
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> extend;
  public java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>> metaData;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return url;
    case 1: return content;
    case 2: return extend;
    case 3: return metaData;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: url = (java.lang.CharSequence)value$; break;
    case 1: content = (java.nio.ByteBuffer)value$; break;
    case 2: extend = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 3: metaData = (java.util.Map<java.lang.CharSequence,java.util.List<java.lang.CharSequence>>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
