/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package kim.spider.schema;

@SuppressWarnings("all")
public class CrawlDatum extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"CrawlDatum\",\"namespace\":\"kim.spider.schema\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"fetchTime\",\"type\":\"long\",\"default\":\"0\"},{\"name\":\"modifiedTime\",\"type\":\"long\",\"default\":\"0\"},{\"name\":\"fetchInterval\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"retries\",\"type\":\"int\",\"default\":\"0\"},{\"name\":\"score\",\"type\":\"float\",\"default\":\"0\"},{\"name\":\"signature\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"MD5\",\"size\":16}]},{\"name\":\"extend\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]},{\"name\":\"metaData\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}]}]}");
  public int status;
  public long fetchTime;
  public long modifiedTime;
  public int fetchInterval;
  public int retries;
  public float score;
  public kim.spider.schema.MD5 signature;
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> extend;
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> metaData;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status;
    case 1: return fetchTime;
    case 2: return modifiedTime;
    case 3: return fetchInterval;
    case 4: return retries;
    case 5: return score;
    case 6: return signature;
    case 7: return extend;
    case 8: return metaData;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status = (java.lang.Integer)value$; break;
    case 1: fetchTime = (java.lang.Long)value$; break;
    case 2: modifiedTime = (java.lang.Long)value$; break;
    case 3: fetchInterval = (java.lang.Integer)value$; break;
    case 4: retries = (java.lang.Integer)value$; break;
    case 5: score = (java.lang.Float)value$; break;
    case 6: signature = (kim.spider.schema.MD5)value$; break;
    case 7: extend = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    case 8: metaData = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
